Java-Nerdery-ChallengeV2 - Extra-challenge - Luis Moroco
ravnhq/Java-Nerdery-ChallengeV2 pull request #4
Opened 2024-11-20 21:14 UTC by luismoroco

2024-11-21 00:19 UTC, sbobadilla8 commented on src/main/java/ChallengeStream.java
> +          };
Can you think of a simpler way of doing this? Using a switch case statement here is a bit of overkill for the required logic, and such constructs are not recommended inside a return statement.

2024-11-21 00:25 UTC, sbobadilla8 commented on src/main/java/ChallengeStream.java
> +          .toList();
This is a very succinct way of calculating the costs, yet, the amount of boilerplate before makes it not worth it really. It's a good use of abstract classes and inheritance, yet that is not the purpose of this exercise and it is not really needed. 
Can you find a way of not needing those class definitions?

2024-11-21 00:27 UTC, sbobadilla8 commented on src/main/java/Challenges.java
> +        }
Why did you choose to use an enum here?

2024-11-21 00:28 UTC, sbobadilla8 commented on src/main/java/Challenges.java
> +            }
While correct, manually formatting strings this way has never been a solid way of doing it. Look into the `format` method of the String class.

2024-11-21 00:34 UTC, sbobadilla8 commented on src/main/java/Challenges.java
> +        BigInteger sum = new BigInteger(BigInteger.ZERO.toByteArray());
Why are you using `toByteArray()` here and in L139? You are just converting it back later in L148. You shouldn't need to use this

2024-11-21 00:35 UTC, sbobadilla8 commented on src/main/java/Challenges.java
> +        BigInteger factorial = new BigInteger(BigInteger.ONE.toByteArray());
Same comment about `toByteArray`

2024-11-21 01:36 UTC, sbobadilla8 commented on src/main/java/meteorology/model/Variable.java
> +  public Double maximum = 0.0;
Minimum and maximum are usually defined as the largest number possible and the smallest number possible, respectively. 
This due to what we are trying to find. Using this defaults here pose problems. Take into account the temperature for example, if our default minimum is 0, what happens when our minimum is 5? It would never register as such. The opposite is true for cold weathers, what it our maximum is -5? 
Review this values and logic around them.

2024-11-21 01:37 UTC, sbobadilla8 commented on src/main/java/meteorology/model/Weather.java
> +  public Double strikes; // I
What do these comments mean?

2024-11-21 01:45 UTC, sbobadilla8 commented on src/main/java/meteorology/model/MeteorologyVariable.java
> +}
I think this is not being used? I couldn't find any references to it in the code you uploaded.

2024-11-21 01:49 UTC, sbobadilla8 commented on src/main/java/meteorology/report/MeteorologyReport.java
> +}
I fail to see the purpose of this class, just because you can define abstract classes it doesn't mean you should use them every time. If an abstract class is short and has just a couple of variables then maybe you can do just fine without it. 
Can you think of a better approach (with less code architecture complexity) to solve this challenge? It's good that you think of abstraction here, but not in the literal sense of an abstract class. Maybe you can _reuse_ a class?

2024-11-21 01:52 UTC, sbobadilla8 commented on src/main/java/ExtraChallenges.java
> +  }
This code is very Pythonesque. In java you should just define the main in one go (in my humble opinion) when it is a single purpose app like this

2024-11-21 01:54 UTC, sbobadilla8 commented on src/main/java/ExtraChallenges.java
> +import meteorology.report.policy.AggregatedMeteorologyReport;
This import is not being used here.

2024-11-21 01:55 UTC, sbobadilla8 requested changes
Overall you have some interesting approaches, yet I think you overcomplicated yourself in several places. Follow the KISS principle.

2024-11-21 01:56 UTC, sbobadilla8 commented
> * Creé una clase llamada **Weather** que se mapea usando Jackson desde el array de objetos en formato JSON. Estos se instancian una a una, lo cual, en manejable por la memoria. Además cuenta con un verificador de **Fields** para evitar procesar los objetos con datos faltantes/nulos.
> * Creé una clase llamada **Report** que contiene un Mapa de **Fields** que son propiedades de Weather que tienen como valor instancias de **Variable** que contiene los datos minimum, average y maximun; además de una función para actualizarlos  y otra para mostrarlo en el formato requerido.
> * Creé una clase abstracta llamada **MeteorologyReport** con dos métodos **process** y **show** para procesar los datos de cada instancia de Weather. Esta tiene dos subclases **AggregatedMeteorologyReport** (Generar un reporte de todo el conjunto de datos) y **DailyMeteorologyReport** (separarlos por fechas DÍAS). Aggregate instancia un Report y obtiene las Fields de las instancias de Weather para utilizar la función **Variable.update()**  para actualizar los valores tomando el nombre de las propiedades. En cuanto a **DailyMeteorologyReport**  crea un HashMap donde **Weather.time** será la key y tendrá asociado una instancia de **AggregatedMeteorologyReport** también implementa **process** , pero verifica que exista la fecha y si no la crea y utiliza **AggregatedMeteorologyReport.process** para actualizar su propio reporte. Para intercambiar las políticas de procesamiento, solo debe intercambiarse la línea 13 del archivo ExtraChallenge **final static MeteorologyReport meteorologyReport = new POLICY;** .

Also this should be in English.

2024-11-21 16:59 UTC, luismoroco commented on src/main/java/meteorology/model/Variable.java
> +  public Double maximum = 0.0;
Although they are initialized to 0.0, they are updated with the first value that comes in to update that variable, as shown in Line 14:

  public void update(Double value) {
    if (count == 0) {
      this.maximum = value;
      this.minimum = value;
    }

    if (value < this.minimum) {
      this.minimum = value;
    }

    if (value > this.maximum) {
      this.maximum = value;
    }

    this.average += value;
    ++this.count;
  }

2024-11-22 02:11 UTC, sbobadilla8 commented on src/main/java/meteorology/model/Variable.java
> +  public Double maximum = 0.0;
I think that if you are a bit smarter about how you initialize those values you can that extra if block, which was also the reason behind my comment.

2024-11-22 02:14 UTC, sbobadilla8 commented on src/main/java/ChallengeStream.java
> +        }
I think that this can be even simpler

2024-11-22 02:25 UTC, sbobadilla8 reviewed
I'm still not fully understanding the way you handle the aggregated and daily report. Maybe we can check that in the office tomorrow.

2024-11-22 03:55 UTC, luismoroco commented on src/main/java/ChallengeStream.java
> +        }
Right, using ternary operators and max

2024-11-22 11:14 UTC, luismoroco commented on src/main/java/meteorology/model/Variable.java
> +  public Double maximum = 0.0;
Thanks for the clarification

2024-11-22 19:38 UTC, sbobadilla8 reviewed
I know you are still making changes in the extra challenge, but everything else looks way better now.

2024-11-27 15:52 UTC, quebin31 commented on src/main/java/ChallengeStream.java
> +        .reduce(0, (a, b) -> a * 10 + b);
Nice

2024-11-27 15:54 UTC, quebin31 commented on src/main/java/Challenges.java
> +
Check `modPow` or `pow`

2024-11-27 15:57 UTC, quebin31 commented on src/main/java/meteorology/model/Variable.java
> +    ++this.count;
nit: `this.count += 1` is more understandable IMO

2024-11-27 16:13 UTC, quebin31 commented
Parsing JSON into a Java class shouldn't need to use reflection from your end, reconsider your approach

2026-01-08 17:37 UTC, closed without merging